### ISSUE TITLE
Configuration in `add/2`

### ISSUE THREAD

**Issue by ruslandoga** [elixir-lang/logger_backends#2]
👋

The docs mention that `add/2` can be used to [pass some configuration](https://github.com/elixir-lang/logger_backends/blob/73df174624cd42209a108208fdcc658d26ab669f/lib/logger_backends.ex#L32) to the new backend, but `opts` [don't appear to be passed along](https://github.com/elixir-lang/logger_backends/blob/953b5ec84904a91a999cf33b212e325163ce4b5f/lib/logger_backends.ex#L210) to the supervisor.

I wonder if it's a typo in the docs or a missing feature in the implementation?

My use case for passing config in `add/2` is the ability to run multiple logger backends for the same backend module. For example, I'm working on a Sentry backend and I'd like to use it to post to multiple DSNs (one on sentry.io, one self-hosted):

```elixir
LoggerBackends.add(SentryBackend, dsn: System.fetch_env!("SENTRY_DSN"), level: :error, metadata: [:request_id, :user_id])
LoggerBackends.add(SentryBackend, dsn: System.fetch_env!("SELF_HOSTED_SENTRY_DSN"), level: :warning, metadata: :all)
```
I guess it won't be possible anyway since the backends are uniqued by the module name. I wonder if something like `:id` could be added to allow for that use-case?

**Comment by josevalim** [comment]
Good find.

In your case you could try something like this:

```elixir
LoggerBackends.add({SentryBackend, 1}, dns: System.fetch_env!("SENTRY_DSN"), level: :error, metadata: [:request_id, :user_id])
LoggerBackends.add({SentryBackend, 2}, dsn: System.fetch_env!("SELF_HOSTED_SENTRY_DSN"), level: :warning, metadata: :all)
```

and then configure both `{SentryBackend, 1}` and `{SentryBackend, 2}` in your config file, but you would need Sentry to support this style too.

**Comment by ruslandoga** [comment]
Thank you!
